### ISSUE TITLE
Build error package javafx.scene.chart does not exist

### ISSUE THREAD

**Issue by sichen1234** [hyperledger-labs/eThaler#24]
I'm trying to use src/CLI/PrepareeThalerClient.sh

To get it to work I had to download gradle 5.1 and then run
$ ~/Downloads/gradle-5.1.1/bin/gradle wrapper --gradle-version 5.1

Then modify your PrepareeThalerClient.sh to change the gradlew to run like
./gradlew build copyJars createeThalerClientScript

But then running it, I get error:
$  sh PrepareeThalerClient.sh
Downloading https://services.gradle.org/distributions/gradle-5.1-bin.zip
.................................................................................

Welcome to Gradle 5.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
/Users/sichen/hyperledger/eThaler/src/CLI/src/main/java/com/swapshub/ethaler/client/ContractAccountUtil.java:12: error: package javafx.scene.chart does not exist
import javafx.scene.chart.StackedAreaChart;
                         ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

<img width="1260" alt="Screen Shot 2020-11-17 at 12 46 50 PM" src="https://user-images.githubusercontent.com/1706353/99445878-06123880-28d3-11eb-9ebc-a6bcbf889d14.png">

**Comment by jagadeeshtmr** [comment]
Have committed files after removing not required import statements. 

Seems the JavaFx package has been removed from Java version 11.  

A fresh attempt for compilation and testing the app could done.

**Comment by opentaps** [comment]
Thanks so much!  That got it to work.

FYI I'm using 
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

on OS X.

**Comment by vipinsun** [comment]
As Mani's fix got it to work
