### ISSUE TITLE
Gas price below configured minimum gas price

### ISSUE THREAD

**Issue by sichen1234** [hyperledger-labs/eThaler#28]
I'm making progress here!

Got the central banker wallet to load and am trying to create a new token, but am getting error message:
Error in processing Central Banker Options EX: Error processing transaction request: Gas price below configured minimum gas price

I think the problem is in ContractAccountUtil.getGasProvider which is currently configured to a gas price of 0.

I increased both the gas price and gas limit and it worked.

Should it be changed to put the gas price and gas limit in the config.properties?

**Comment by mmani99** [comment]
For private Enterprise Ethereum, gas price/limit becomes irrelevant.  
For HL Besu, you can configure gas to have zero impact.
That's why you see the limits set that way.
Mani|SwapsHub|212-742-1800|mani@swapshub.com

**Comment by opentaps** [comment]
OK.  I've already increased the besu gas limit by changing
    "gasLimit": "0x1fffffffffffff",

in ibftConfigFile.json and genesis.json

We'll look into removing the gas price in our network set up as well.

-----
Si Chen
Open Source Strategies, Inc.

Video: Fighting Climate Change with Blockchain and Open Source
<https://youtu.be/NgxNWXa_IjE>
